[package]
name = "monitui"
version = "0.2.0"
edition = "2021"
description = "A TUI for configuring Hyprland monitors"

[dependencies]
ratatui = { version = "0.27", features = ["all-widgets"] }
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5"
